language: php
php:
  - 5.3
  - 5.4
  - 5.5
rvm:
  - 2.0.0p247

before_install:
  - gem update --system
  - gem install compass-aurora-os
install:
  - git reset --hard
  - git clean -dxf
  - sudo apt-get update > /dev/null
  - sudo apt-get install php5-curl php5-gd > /dev/null
  - composer global require drush/drush:6.*
  - sudo drush
  - sudo chown -R $USER:$USER /home/$USER/.drush
script:
  - bin/make-install-profile client_xyz xyz_foobar "Web app ABC" "Client XYZ's ABC app enables users to browse a database of records."
